#Mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baeunday_app?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: dbqudgns24

  jwt:
    secret: fnxmdlavorxmzjarhdtkdldpvldjskswjswjdxhddlfemdrkwmdkaaaaaaaaaaaaa

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#H2
#spring:
#  sql:
#    init:
#      mode: always
#      platform: h2
#      username: sa
#      data-locations: classpath*:db/data.sql
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:baeun
#    username: sa
#    password:
#
#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none
#    generate-ddl: true
#    show-sql: true


logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

